### ISSUE TITLE
.setOptions method in entity.js missing

### ISSUE THREAD

**Issue by maulberto3** [MicheleBertoli/react-gmaps#116]
Hi, that.

**Comment by maulberto3** [comment]
Note: Upon research, I believe you got it from the Google Maps API, so there is no reason to define it right?

**Comment by MicheleBertoli** [comment]
Hello @maulberto3, thank for opening this issue.
Is there any particular reason why you would define `setOption`?
The component is using [setOption](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/entity.js#L22) under the hood and it provides an abstraction over the Google Maps options, so that they can be passed as props.
