### ISSUE TITLE
Avoid re-rendering of map entities 

### ISSUE THREAD

**Issue by TGMorais** [MicheleBertoli/react-gmaps#38]
Hello,

I've been using react-gmaps for a little while, and I've notice that in some use cases, there is no way to prevent certain re-renders of map entities, like `<Marker>`.

Say for example one would have a component like so:

```javascript
//mygmapscomponent.jsx

  render() {
      let {height, coords, zoom, markers} = this.props;

      return (
        <div className="gmap-component" style={{ position: 'relative' }}>
          <Gmaps
             width={'100%'}
             height={height}
             lat={coords.lat}
             lng={coords.lng}
             zoom={zoom}
             loadingMessage={'loading'}
             onMapCreated={this.onMapCreated}>
             { this.renderMakers( markers ) }
          </Gmaps>
          { this.renderLegend(this.state.legendItems) }
        </div>
      )
  }


  renderLegend(items) {
    return (
      <div className="map-legend">
        { items.map( this.renderLegendItem, this) }
       </div>
    )
  }
```

If for some reason the component `render()` is called again, say because of a change in the lengend state, the `markers` will also be re-render ( which will make the markers flash/flicker on the map)

This is, from what I can see, because `componentDidMount` in [`src\components\entity.js`](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/entity.js#L13) re-sets the entities options (like the google map object) 

I would suggest allowing to pass a prop to the entity like `shouldUpdate` that would prevent that from happening if it would return `false`, much like react's own `shouldComponentUpdate`, something like this:

```javascript
//src/components/entity.js
    componentWillReceiveProps(nextProps) {
      if(typeof this.props.shouldUpdate === "function") {
          if( !this.props.shoudUpdate(this.props, nextProps) )
            return;
      }
      const options = this.getOptions(nextProps);
      this.entity.setOptions(options);
    },
```

This would prevent allow us to check if we really want the entities to update or not, which in my case would prevent `markers/etc` from flickering on the map each time the component has to `render()` for an unrelated reason

**Comment by MicheleBertoli** [comment]
Hello @TGMorais,
thank you very much for your contribution.

I managed to [reproduce](https://gist.github.com/MicheleBertoli/c1bc19fc4f5b37f5c5a6) and [fix](https://github.com/MicheleBertoli/react-gmaps/releases/tag/1.4.2) the issue.

**Before**
![before](https://cloud.githubusercontent.com/assets/1308971/13092073/0fbd21fa-d4f6-11e5-8af1-e2ace5318c58.gif)

**After**
![after](https://cloud.githubusercontent.com/assets/1308971/13092080/144497f8-d4f6-11e5-8f99-1b0852f155ea.gif)

Instead of adding a new prop, as you suggested, I added a check (that I was [already doing](https://github.com/MicheleBertoli/react-gmaps/blob/master/src/components/gmaps.js#L33) on the Gmaps component) to see if the props are changed.

**Comment by TGMorais** [comment]
Thank you! :+1: :+1:
