### ISSUE TITLE
onLoad event?

### ISSUE THREAD

**Issue by MatthewKosloski** [MicheleBertoli/react-gmaps#63]
Is there a way to call a function when the map has fully loaded?  I don't want to display "loading..." text or watch the map load the tiles. 

Thanks!

**Comment by MicheleBertoli** [comment]
Hello @MatthewKosloski 
this problem is more related to the Google Maps SDK rather than the component itself.

I found [this](http://stackoverflow.com/a/7262773/1712895) questions on Stack Overflow and implemented a solution:

![idle](https://cloud.githubusercontent.com/assets/1308971/19233824/e2b56b8c-8edf-11e6-9a94-0495cfb1efaa.gif)
[source](https://gist.github.com/MicheleBertoli/a42095f0cc6e31e5f2d0dfda3bc7dbcd)

Hope this helps!
