### ISSUE TITLE
How to add OverlayView with react-gmaps?

### ISSUE THREAD

**Issue by feux07** [MicheleBertoli/react-gmaps#81]
Hey, everyone!

Can we use OverlayView with react-gmaps like this [example](https://tomchentw.github.io/react-google-maps/basics/overlay-view) ?

**Comment by MicheleBertoli** [comment]
Hello @feux07,
at the moment there's no `Overlay` component in `react-gmaps` (PRs are welcome :)).

Luckily, there's the `onMapCreated` callback which provides you the actual map instance.
At that point, you can do all the things you do with the regular Google Maps SDK (e.g. adding overlays).

For instance, following [this](https://developers.google.com/maps/documentation/javascript/examples/overlay-simple) official example, instead of creating the map like:

```javascript
       var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: {lat: 62.323907, lng: -150.109291},
          mapTypeId: 'satellite'
        });
```

You receive it from the `mapCreated` event, and you can add any overlay to it:

```jsx
<Gmaps onMapCreated={this.handleMapCreated} ... />
```

```javascript
handleMapCreate(map) {
  // ... 
  overlay = new USGSOverlay(bounds, srcImage, map);
}
```

Hope this helps!

**Comment by feux07** [comment]
Hi @MicheleBertoli,

I forgot to thanks, for your quick reply and your awesome component.

Have a nice working day
